/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as account from "../account.js";
import type * as activity from "../activity.js";
import type * as adminSeed from "../adminSeed.js";
import type * as adminUsers from "../adminUsers.js";
import type * as announcements from "../announcements.js";
import type * as appConfig from "../appConfig.js";
import type * as assignmentScores from "../assignmentScores.js";
import type * as assignments from "../assignments.js";
import type * as attendance from "../attendance.js";
import type * as auth from "../auth.js";
import type * as authz from "../authz.js";
import type * as authzBackfill from "../authzBackfill.js";
import type * as behaviorFolders from "../behaviorFolders.js";
import type * as behaviors from "../behaviors.js";
import type * as billing from "../billing.js";
import type * as billingActions from "../billingActions.js";
import type * as calendar from "../calendar.js";
import type * as classDeletion from "../classDeletion.js";
import type * as classPermissions from "../classPermissions.js";
import type * as classUserSettings from "../classUserSettings.js";
import type * as classes from "../classes.js";
import type * as classesBackfill from "../classesBackfill.js";
import type * as classroomScreen from "../classroomScreen.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as equitableAssigners from "../equitableAssigners.js";
import type * as expectations from "../expectations.js";
import type * as feedback from "../feedback.js";
import type * as files from "../files.js";
import type * as filesInternal from "../filesInternal.js";
import type * as githubCloneSync from "../githubCloneSync.js";
import type * as gradeScales from "../gradeScales.js";
import type * as gradedSubjects from "../gradedSubjects.js";
import type * as groups from "../groups.js";
import type * as http from "../http.js";
import type * as joinCodes from "../joinCodes.js";
import type * as lib_accountDeletion from "../lib/accountDeletion.js";
import type * as lib_activity_classActivity from "../lib/activity/classActivity.js";
import type * as lib_admin from "../lib/admin.js";
import type * as lib_announcementLimits from "../lib/announcementLimits.js";
import type * as lib_announcements_announcementLimits from "../lib/announcements/announcementLimits.js";
import type * as lib_announcementsCleanup from "../lib/announcementsCleanup.js";
import type * as lib_assigners_equitableAssign from "../lib/assigners/equitableAssign.js";
import type * as lib_assigners_equitableAssignerSchema from "../lib/assigners/equitableAssignerSchema.js";
import type * as lib_assigners_equitableGenderBuckets from "../lib/assigners/equitableGenderBuckets.js";
import type * as lib_assigners_equitableManualSlots from "../lib/assigners/equitableManualSlots.js";
import type * as lib_assigners_equitableRosterMatrix from "../lib/assigners/equitableRosterMatrix.js";
import type * as lib_assigners_randomAssign from "../lib/assigners/randomAssign.js";
import type * as lib_assigners_randomAssignerSchema from "../lib/assigners/randomAssignerSchema.js";
import type * as lib_assigners_runAssignmentProjection from "../lib/assigners/runAssignmentProjection.js";
import type * as lib_assignmentScoresCleanup from "../lib/assignmentScoresCleanup.js";
import type * as lib_assignments_dueDateKey from "../lib/assignments/dueDateKey.js";
import type * as lib_assignmentsCleanup from "../lib/assignmentsCleanup.js";
import type * as lib_attendance_attendanceHistory from "../lib/attendance/attendanceHistory.js";
import type * as lib_attendanceCleanup from "../lib/attendanceCleanup.js";
import type * as lib_attendanceHistory from "../lib/attendanceHistory.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_auth_admin from "../lib/auth/admin.js";
import type * as lib_auth_auth from "../lib/auth/auth.js";
import type * as lib_auth_authzModel from "../lib/auth/authzModel.js";
import type * as lib_auth_classPermissionOverrides from "../lib/auth/classPermissionOverrides.js";
import type * as lib_auth_customFunctions from "../lib/auth/customFunctions.js";
import type * as lib_auth_fileAccess from "../lib/auth/fileAccess.js";
import type * as lib_auth_guardianLinks from "../lib/auth/guardianLinks.js";
import type * as lib_auth_permissionSnapshot from "../lib/auth/permissionSnapshot.js";
import type * as lib_authzModel from "../lib/authzModel.js";
import type * as lib_avatarUrl from "../lib/avatarUrl.js";
import type * as lib_behaviorsCleanup from "../lib/behaviorsCleanup.js";
import type * as lib_billing_billingGuards from "../lib/billing/billingGuards.js";
import type * as lib_billing_entitlement from "../lib/billing/entitlement.js";
import type * as lib_billing_polarEnv from "../lib/billing/polarEnv.js";
import type * as lib_billing_polarErrors from "../lib/billing/polarErrors.js";
import type * as lib_billing_polarSubscription from "../lib/billing/polarSubscription.js";
import type * as lib_billing_presenceEnabled from "../lib/billing/presenceEnabled.js";
import type * as lib_billing_selfHosted from "../lib/billing/selfHosted.js";
import type * as lib_billing_trial from "../lib/billing/trial.js";
import type * as lib_billingGuards from "../lib/billingGuards.js";
import type * as lib_calendar_audience from "../lib/calendar/audience.js";
import type * as lib_calendar_calendarEventSchema from "../lib/calendar/calendarEventSchema.js";
import type * as lib_calendar_dateKey from "../lib/calendar/dateKey.js";
import type * as lib_calendar_eventHref from "../lib/calendar/eventHref.js";
import type * as lib_calendar_monthGrid from "../lib/calendar/monthGrid.js";
import type * as lib_calendar_overlap from "../lib/calendar/overlap.js";
import type * as lib_calendar_reminders from "../lib/calendar/reminders.js";
import type * as lib_calendar_timeZone from "../lib/calendar/timeZone.js";
import type * as lib_calendar_timezoneFormSchema from "../lib/calendar/timezoneFormSchema.js";
import type * as lib_classActivity from "../lib/classActivity.js";
import type * as lib_classPermissionOverrides from "../lib/classPermissionOverrides.js";
import type * as lib_classroomScreen_activeSession from "../lib/classroomScreen/activeSession.js";
import type * as lib_classroomScreen_audioCues from "../lib/classroomScreen/audioCues.js";
import type * as lib_classroomScreen_audioCuesSchema from "../lib/classroomScreen/audioCuesSchema.js";
import type * as lib_classroomScreen_bgTransitions from "../lib/classroomScreen/bgTransitions.js";
import type * as lib_classroomScreen_clockSettingsDefaults from "../lib/classroomScreen/clockSettingsDefaults.js";
import type * as lib_classroomScreen_currentLesson from "../lib/classroomScreen/currentLesson.js";
import type * as lib_classroomScreen_rotationSchema from "../lib/classroomScreen/rotationSchema.js";
import type * as lib_classroomScreen_timerUtils from "../lib/classroomScreen/timerUtils.js";
import type * as lib_cleanup_announcementsCleanup from "../lib/cleanup/announcementsCleanup.js";
import type * as lib_cleanup_assignmentScoresCleanup from "../lib/cleanup/assignmentScoresCleanup.js";
import type * as lib_cleanup_assignmentsCleanup from "../lib/cleanup/assignmentsCleanup.js";
import type * as lib_cleanup_attendanceCleanup from "../lib/cleanup/attendanceCleanup.js";
import type * as lib_cleanup_behaviorsCleanup from "../lib/cleanup/behaviorsCleanup.js";
import type * as lib_cleanup_calendarCleanup from "../lib/cleanup/calendarCleanup.js";
import type * as lib_cleanup_classroomScreenCleanup from "../lib/cleanup/classroomScreenCleanup.js";
import type * as lib_cleanup_deleteClass from "../lib/cleanup/deleteClass.js";
import type * as lib_cleanup_equitableAssignersCleanup from "../lib/cleanup/equitableAssignersCleanup.js";
import type * as lib_cleanup_expectationsCleanup from "../lib/cleanup/expectationsCleanup.js";
import type * as lib_cleanup_filesCleanup from "../lib/cleanup/filesCleanup.js";
import type * as lib_cleanup_filesCleanupBatch from "../lib/cleanup/filesCleanupBatch.js";
import type * as lib_cleanup_gradeScalesCleanup from "../lib/cleanup/gradeScalesCleanup.js";
import type * as lib_cleanup_gradedSubjectsCleanup from "../lib/cleanup/gradedSubjectsCleanup.js";
import type * as lib_cleanup_groupsCleanup from "../lib/cleanup/groupsCleanup.js";
import type * as lib_cleanup_joinCodesCleanup from "../lib/cleanup/joinCodesCleanup.js";
import type * as lib_cleanup_notificationHistoryCleanup from "../lib/cleanup/notificationHistoryCleanup.js";
import type * as lib_cleanup_pointsCleanup from "../lib/cleanup/pointsCleanup.js";
import type * as lib_cleanup_randomAssignersCleanup from "../lib/cleanup/randomAssignersCleanup.js";
import type * as lib_cleanup_razCleanup from "../lib/cleanup/razCleanup.js";
import type * as lib_cleanup_rewardsCleanup from "../lib/cleanup/rewardsCleanup.js";
import type * as lib_cleanup_seatingCleanup from "../lib/cleanup/seatingCleanup.js";
import type * as lib_cleanup_tasksCleanup from "../lib/cleanup/tasksCleanup.js";
import type * as lib_cleanup_timetableCleanup from "../lib/cleanup/timetableCleanup.js";
import type * as lib_customFunctions from "../lib/customFunctions.js";
import type * as lib_dashboard_dashboard from "../lib/dashboard/dashboard.js";
import type * as lib_dueDateKey from "../lib/dueDateKey.js";
import type * as lib_entitlement from "../lib/entitlement.js";
import type * as lib_equitableAssignersCleanup from "../lib/equitableAssignersCleanup.js";
import type * as lib_expectationsCleanup from "../lib/expectationsCleanup.js";
import type * as lib_fileAccess from "../lib/fileAccess.js";
import type * as lib_files_classFileRefs from "../lib/files/classFileRefs.js";
import type * as lib_files_uploadPresets from "../lib/files/uploadPresets.js";
import type * as lib_files_zipEntries from "../lib/files/zipEntries.js";
import type * as lib_filesCleanup from "../lib/filesCleanup.js";
import type * as lib_gradeScales_defaults from "../lib/gradeScales/defaults.js";
import type * as lib_gradeScales_gradeScaleSchema from "../lib/gradeScales/gradeScaleSchema.js";
import type * as lib_gradeScales_normalize from "../lib/gradeScales/normalize.js";
import type * as lib_gradeScalesCleanup from "../lib/gradeScalesCleanup.js";
import type * as lib_gradedSubjects_gradedSubjectSchema from "../lib/gradedSubjects/gradedSubjectSchema.js";
import type * as lib_gradedSubjects_normalize from "../lib/gradedSubjects/normalize.js";
import type * as lib_gradedSubjectsCleanup from "../lib/gradedSubjectsCleanup.js";
import type * as lib_groupsCleanup from "../lib/groupsCleanup.js";
import type * as lib_guardianLinks from "../lib/guardianLinks.js";
import type * as lib_i18n_languages from "../lib/i18n/languages.js";
import type * as lib_joinCodesCleanup from "../lib/joinCodesCleanup.js";
import type * as lib_languages from "../lib/languages.js";
import type * as lib_linkAccessibility from "../lib/linkAccessibility.js";
import type * as lib_links_linkAccessibility from "../lib/links/linkAccessibility.js";
import type * as lib_notifications_client from "../lib/notifications/client.js";
import type * as lib_notifications_history from "../lib/notifications/history.js";
import type * as lib_permissionSnapshot from "../lib/permissionSnapshot.js";
import type * as lib_platform_accountDeletion from "../lib/platform/accountDeletion.js";
import type * as lib_platform_usageTracking from "../lib/platform/usageTracking.js";
import type * as lib_points_notifyPointsBadgeAlert from "../lib/points/notifyPointsBadgeAlert.js";
import type * as lib_points_pointsBadgeAlert from "../lib/points/pointsBadgeAlert.js";
import type * as lib_points_pointsBadgeAlertSchema from "../lib/points/pointsBadgeAlertSchema.js";
import type * as lib_points_pointsBadgeWindow from "../lib/points/pointsBadgeWindow.js";
import type * as lib_points_pointsLedger from "../lib/points/pointsLedger.js";
import type * as lib_points_pointsRoster from "../lib/points/pointsRoster.js";
import type * as lib_pointsBadgeWindow from "../lib/pointsBadgeWindow.js";
import type * as lib_pointsCleanup from "../lib/pointsCleanup.js";
import type * as lib_pointsRoster from "../lib/pointsRoster.js";
import type * as lib_polarEnv from "../lib/polarEnv.js";
import type * as lib_polarErrors from "../lib/polarErrors.js";
import type * as lib_polarSubscription from "../lib/polarSubscription.js";
import type * as lib_presenceEnabled from "../lib/presenceEnabled.js";
import type * as lib_purchaseLimit from "../lib/purchaseLimit.js";
import type * as lib_randomAssignersCleanup from "../lib/randomAssignersCleanup.js";
import type * as lib_rateLimit_rateLimitActions from "../lib/rateLimit/rateLimitActions.js";
import type * as lib_rateLimit_rateLimiter from "../lib/rateLimit/rateLimiter.js";
import type * as lib_rateLimitActions from "../lib/rateLimitActions.js";
import type * as lib_rateLimiter from "../lib/rateLimiter.js";
import type * as lib_raz_razAutoRti from "../lib/raz/razAutoRti.js";
import type * as lib_raz_razLevels from "../lib/raz/razLevels.js";
import type * as lib_razAutoRti from "../lib/razAutoRti.js";
import type * as lib_razLevels from "../lib/razLevels.js";
import type * as lib_release_scheduledRelease from "../lib/release/scheduledRelease.js";
import type * as lib_rewards_purchaseLimit from "../lib/rewards/purchaseLimit.js";
import type * as lib_rewardsCleanup from "../lib/rewardsCleanup.js";
import type * as lib_roster_avatarUrl from "../lib/roster/avatarUrl.js";
import type * as lib_roster_rosterNameFormat from "../lib/roster/rosterNameFormat.js";
import type * as lib_roster_seedTestStudents from "../lib/roster/seedTestStudents.js";
import type * as lib_roster_studentRosters from "../lib/roster/studentRosters.js";
import type * as lib_roster_userImage from "../lib/roster/userImage.js";
import type * as lib_rosterNameFormat from "../lib/rosterNameFormat.js";
import type * as lib_seatChartGeometry from "../lib/seatChartGeometry.js";
import type * as lib_seatChartLogic from "../lib/seatChartLogic.js";
import type * as lib_seatLayoutCopy from "../lib/seatLayoutCopy.js";
import type * as lib_seatLayoutTeamSync from "../lib/seatLayoutTeamSync.js";
import type * as lib_seating_classroomLayouts from "../lib/seating/classroomLayouts.js";
import type * as lib_seating_diagnose from "../lib/seating/diagnose.js";
import type * as lib_seating_failureEvidence from "../lib/seating/failureEvidence.js";
import type * as lib_seating_gender from "../lib/seating/gender.js";
import type * as lib_seating_history from "../lib/seating/history.js";
import type * as lib_seating_historyKeys from "../lib/seating/historyKeys.js";
import type * as lib_seating_layoutRosterMatrix from "../lib/seating/layoutRosterMatrix.js";
import type * as lib_seating_layoutStudentHistory from "../lib/seating/layoutStudentHistory.js";
import type * as lib_seating_mergeAssignments from "../lib/seating/mergeAssignments.js";
import type * as lib_seating_pipeline from "../lib/seating/pipeline.js";
import type * as lib_seating_predicates from "../lib/seating/predicates.js";
import type * as lib_seating_runSeatingAlgorithm from "../lib/seating/runSeatingAlgorithm.js";
import type * as lib_seating_scope from "../lib/seating/scope.js";
import type * as lib_seating_seatChartGeometry from "../lib/seating/seatChartGeometry.js";
import type * as lib_seating_seatChartLogic from "../lib/seating/seatChartLogic.js";
import type * as lib_seating_seatLayoutCopy from "../lib/seating/seatLayoutCopy.js";
import type * as lib_seating_seatLayoutTeamSync from "../lib/seating/seatLayoutTeamSync.js";
import type * as lib_seating_seatingScenarios from "../lib/seating/seatingScenarios.js";
import type * as lib_seating_seatingSeeds from "../lib/seating/seatingSeeds.js";
import type * as lib_seating_seatingTestHelpers from "../lib/seating/seatingTestHelpers.js";
import type * as lib_seating_settings from "../lib/seating/settings.js";
import type * as lib_seating_solve from "../lib/seating/solve.js";
import type * as lib_seating_types from "../lib/seating/types.js";
import type * as lib_seating_validateOutput from "../lib/seating/validateOutput.js";
import type * as lib_seating_validators from "../lib/seating/validators.js";
import type * as lib_seedTestStudents from "../lib/seedTestStudents.js";
import type * as lib_selfHosted from "../lib/selfHosted.js";
import type * as lib_studentRosters from "../lib/studentRosters.js";
import type * as lib_tasks_migrateWorksheetImage from "../lib/tasks/migrateWorksheetImage.js";
import type * as lib_tasks_taskSchema from "../lib/tasks/taskSchema.js";
import type * as lib_tasksCleanup from "../lib/tasksCleanup.js";
import type * as lib_timetable_importFromClass from "../lib/timetable/importFromClass.js";
import type * as lib_timetable_lessonEvents from "../lib/timetable/lessonEvents.js";
import type * as lib_timetable_sectionItems from "../lib/timetable/sectionItems.js";
import type * as lib_timetable_sectionMigration from "../lib/timetable/sectionMigration.js";
import type * as lib_timetable_slotDisableScope from "../lib/timetable/slotDisableScope.js";
import type * as lib_timetable_slotLinks from "../lib/timetable/slotLinks.js";
import type * as lib_timetable_slotTiming from "../lib/timetable/slotTiming.js";
import type * as lib_timetable_timetableFormSchema from "../lib/timetable/timetableFormSchema.js";
import type * as lib_timetable_timetableSchema from "../lib/timetable/timetableSchema.js";
import type * as lib_trial from "../lib/trial.js";
import type * as lib_uploadPresets from "../lib/uploadPresets.js";
import type * as lib_usageTracking from "../lib/usageTracking.js";
import type * as lib_userImage from "../lib/userImage.js";
import type * as lib_zipEntries from "../lib/zipEntries.js";
import type * as linkAccessibility from "../linkAccessibility.js";
import type * as members from "../members.js";
import type * as migrations from "../migrations.js";
import type * as notificationHistoryBackfill from "../notificationHistoryBackfill.js";
import type * as notificationHooks from "../notificationHooks.js";
import type * as notifications from "../notifications.js";
import type * as permissions from "../permissions.js";
import type * as points from "../points.js";
import type * as polar from "../polar.js";
import type * as polarReconcile from "../polarReconcile.js";
import type * as presence from "../presence.js";
import type * as push from "../push.js";
import type * as pushActions from "../pushActions.js";
import type * as pushInternal from "../pushInternal.js";
import type * as randomAssigners from "../randomAssigners.js";
import type * as raz from "../raz.js";
import type * as rewardFolders from "../rewardFolders.js";
import type * as rewards from "../rewards.js";
import type * as seatCharts from "../seatCharts.js";
import type * as seatChartsRepair from "../seatChartsRepair.js";
import type * as seatConstraints from "../seatConstraints.js";
import type * as seatLayoutAggregatesBackfill from "../seatLayoutAggregatesBackfill.js";
import type * as seatLayoutGenderParityBackfill from "../seatLayoutGenderParityBackfill.js";
import type * as seatLayouts from "../seatLayouts.js";
import type * as studentRosters from "../studentRosters.js";
import type * as tasks from "../tasks.js";
import type * as timetable from "../timetable.js";
import type * as trial from "../trial.js";
import type * as trialBackfill from "../trialBackfill.js";
import type * as usage from "../usage.js";
import type * as users from "../users.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  account: typeof account;
  activity: typeof activity;
  adminSeed: typeof adminSeed;
  adminUsers: typeof adminUsers;
  announcements: typeof announcements;
  appConfig: typeof appConfig;
  assignmentScores: typeof assignmentScores;
  assignments: typeof assignments;
  attendance: typeof attendance;
  auth: typeof auth;
  authz: typeof authz;
  authzBackfill: typeof authzBackfill;
  behaviorFolders: typeof behaviorFolders;
  behaviors: typeof behaviors;
  billing: typeof billing;
  billingActions: typeof billingActions;
  calendar: typeof calendar;
  classDeletion: typeof classDeletion;
  classPermissions: typeof classPermissions;
  classUserSettings: typeof classUserSettings;
  classes: typeof classes;
  classesBackfill: typeof classesBackfill;
  classroomScreen: typeof classroomScreen;
  crons: typeof crons;
  dashboard: typeof dashboard;
  equitableAssigners: typeof equitableAssigners;
  expectations: typeof expectations;
  feedback: typeof feedback;
  files: typeof files;
  filesInternal: typeof filesInternal;
  githubCloneSync: typeof githubCloneSync;
  gradeScales: typeof gradeScales;
  gradedSubjects: typeof gradedSubjects;
  groups: typeof groups;
  http: typeof http;
  joinCodes: typeof joinCodes;
  "lib/accountDeletion": typeof lib_accountDeletion;
  "lib/activity/classActivity": typeof lib_activity_classActivity;
  "lib/admin": typeof lib_admin;
  "lib/announcementLimits": typeof lib_announcementLimits;
  "lib/announcements/announcementLimits": typeof lib_announcements_announcementLimits;
  "lib/announcementsCleanup": typeof lib_announcementsCleanup;
  "lib/assigners/equitableAssign": typeof lib_assigners_equitableAssign;
  "lib/assigners/equitableAssignerSchema": typeof lib_assigners_equitableAssignerSchema;
  "lib/assigners/equitableGenderBuckets": typeof lib_assigners_equitableGenderBuckets;
  "lib/assigners/equitableManualSlots": typeof lib_assigners_equitableManualSlots;
  "lib/assigners/equitableRosterMatrix": typeof lib_assigners_equitableRosterMatrix;
  "lib/assigners/randomAssign": typeof lib_assigners_randomAssign;
  "lib/assigners/randomAssignerSchema": typeof lib_assigners_randomAssignerSchema;
  "lib/assigners/runAssignmentProjection": typeof lib_assigners_runAssignmentProjection;
  "lib/assignmentScoresCleanup": typeof lib_assignmentScoresCleanup;
  "lib/assignments/dueDateKey": typeof lib_assignments_dueDateKey;
  "lib/assignmentsCleanup": typeof lib_assignmentsCleanup;
  "lib/attendance/attendanceHistory": typeof lib_attendance_attendanceHistory;
  "lib/attendanceCleanup": typeof lib_attendanceCleanup;
  "lib/attendanceHistory": typeof lib_attendanceHistory;
  "lib/auth": typeof lib_auth;
  "lib/auth/admin": typeof lib_auth_admin;
  "lib/auth/auth": typeof lib_auth_auth;
  "lib/auth/authzModel": typeof lib_auth_authzModel;
  "lib/auth/classPermissionOverrides": typeof lib_auth_classPermissionOverrides;
  "lib/auth/customFunctions": typeof lib_auth_customFunctions;
  "lib/auth/fileAccess": typeof lib_auth_fileAccess;
  "lib/auth/guardianLinks": typeof lib_auth_guardianLinks;
  "lib/auth/permissionSnapshot": typeof lib_auth_permissionSnapshot;
  "lib/authzModel": typeof lib_authzModel;
  "lib/avatarUrl": typeof lib_avatarUrl;
  "lib/behaviorsCleanup": typeof lib_behaviorsCleanup;
  "lib/billing/billingGuards": typeof lib_billing_billingGuards;
  "lib/billing/entitlement": typeof lib_billing_entitlement;
  "lib/billing/polarEnv": typeof lib_billing_polarEnv;
  "lib/billing/polarErrors": typeof lib_billing_polarErrors;
  "lib/billing/polarSubscription": typeof lib_billing_polarSubscription;
  "lib/billing/presenceEnabled": typeof lib_billing_presenceEnabled;
  "lib/billing/selfHosted": typeof lib_billing_selfHosted;
  "lib/billing/trial": typeof lib_billing_trial;
  "lib/billingGuards": typeof lib_billingGuards;
  "lib/calendar/audience": typeof lib_calendar_audience;
  "lib/calendar/calendarEventSchema": typeof lib_calendar_calendarEventSchema;
  "lib/calendar/dateKey": typeof lib_calendar_dateKey;
  "lib/calendar/eventHref": typeof lib_calendar_eventHref;
  "lib/calendar/monthGrid": typeof lib_calendar_monthGrid;
  "lib/calendar/overlap": typeof lib_calendar_overlap;
  "lib/calendar/reminders": typeof lib_calendar_reminders;
  "lib/calendar/timeZone": typeof lib_calendar_timeZone;
  "lib/calendar/timezoneFormSchema": typeof lib_calendar_timezoneFormSchema;
  "lib/classActivity": typeof lib_classActivity;
  "lib/classPermissionOverrides": typeof lib_classPermissionOverrides;
  "lib/classroomScreen/activeSession": typeof lib_classroomScreen_activeSession;
  "lib/classroomScreen/audioCues": typeof lib_classroomScreen_audioCues;
  "lib/classroomScreen/audioCuesSchema": typeof lib_classroomScreen_audioCuesSchema;
  "lib/classroomScreen/bgTransitions": typeof lib_classroomScreen_bgTransitions;
  "lib/classroomScreen/clockSettingsDefaults": typeof lib_classroomScreen_clockSettingsDefaults;
  "lib/classroomScreen/currentLesson": typeof lib_classroomScreen_currentLesson;
  "lib/classroomScreen/rotationSchema": typeof lib_classroomScreen_rotationSchema;
  "lib/classroomScreen/timerUtils": typeof lib_classroomScreen_timerUtils;
  "lib/cleanup/announcementsCleanup": typeof lib_cleanup_announcementsCleanup;
  "lib/cleanup/assignmentScoresCleanup": typeof lib_cleanup_assignmentScoresCleanup;
  "lib/cleanup/assignmentsCleanup": typeof lib_cleanup_assignmentsCleanup;
  "lib/cleanup/attendanceCleanup": typeof lib_cleanup_attendanceCleanup;
  "lib/cleanup/behaviorsCleanup": typeof lib_cleanup_behaviorsCleanup;
  "lib/cleanup/calendarCleanup": typeof lib_cleanup_calendarCleanup;
  "lib/cleanup/classroomScreenCleanup": typeof lib_cleanup_classroomScreenCleanup;
  "lib/cleanup/deleteClass": typeof lib_cleanup_deleteClass;
  "lib/cleanup/equitableAssignersCleanup": typeof lib_cleanup_equitableAssignersCleanup;
  "lib/cleanup/expectationsCleanup": typeof lib_cleanup_expectationsCleanup;
  "lib/cleanup/filesCleanup": typeof lib_cleanup_filesCleanup;
  "lib/cleanup/filesCleanupBatch": typeof lib_cleanup_filesCleanupBatch;
  "lib/cleanup/gradeScalesCleanup": typeof lib_cleanup_gradeScalesCleanup;
  "lib/cleanup/gradedSubjectsCleanup": typeof lib_cleanup_gradedSubjectsCleanup;
  "lib/cleanup/groupsCleanup": typeof lib_cleanup_groupsCleanup;
  "lib/cleanup/joinCodesCleanup": typeof lib_cleanup_joinCodesCleanup;
  "lib/cleanup/notificationHistoryCleanup": typeof lib_cleanup_notificationHistoryCleanup;
  "lib/cleanup/pointsCleanup": typeof lib_cleanup_pointsCleanup;
  "lib/cleanup/randomAssignersCleanup": typeof lib_cleanup_randomAssignersCleanup;
  "lib/cleanup/razCleanup": typeof lib_cleanup_razCleanup;
  "lib/cleanup/rewardsCleanup": typeof lib_cleanup_rewardsCleanup;
  "lib/cleanup/seatingCleanup": typeof lib_cleanup_seatingCleanup;
  "lib/cleanup/tasksCleanup": typeof lib_cleanup_tasksCleanup;
  "lib/cleanup/timetableCleanup": typeof lib_cleanup_timetableCleanup;
  "lib/customFunctions": typeof lib_customFunctions;
  "lib/dashboard/dashboard": typeof lib_dashboard_dashboard;
  "lib/dueDateKey": typeof lib_dueDateKey;
  "lib/entitlement": typeof lib_entitlement;
  "lib/equitableAssignersCleanup": typeof lib_equitableAssignersCleanup;
  "lib/expectationsCleanup": typeof lib_expectationsCleanup;
  "lib/fileAccess": typeof lib_fileAccess;
  "lib/files/classFileRefs": typeof lib_files_classFileRefs;
  "lib/files/uploadPresets": typeof lib_files_uploadPresets;
  "lib/files/zipEntries": typeof lib_files_zipEntries;
  "lib/filesCleanup": typeof lib_filesCleanup;
  "lib/gradeScales/defaults": typeof lib_gradeScales_defaults;
  "lib/gradeScales/gradeScaleSchema": typeof lib_gradeScales_gradeScaleSchema;
  "lib/gradeScales/normalize": typeof lib_gradeScales_normalize;
  "lib/gradeScalesCleanup": typeof lib_gradeScalesCleanup;
  "lib/gradedSubjects/gradedSubjectSchema": typeof lib_gradedSubjects_gradedSubjectSchema;
  "lib/gradedSubjects/normalize": typeof lib_gradedSubjects_normalize;
  "lib/gradedSubjectsCleanup": typeof lib_gradedSubjectsCleanup;
  "lib/groupsCleanup": typeof lib_groupsCleanup;
  "lib/guardianLinks": typeof lib_guardianLinks;
  "lib/i18n/languages": typeof lib_i18n_languages;
  "lib/joinCodesCleanup": typeof lib_joinCodesCleanup;
  "lib/languages": typeof lib_languages;
  "lib/linkAccessibility": typeof lib_linkAccessibility;
  "lib/links/linkAccessibility": typeof lib_links_linkAccessibility;
  "lib/notifications/client": typeof lib_notifications_client;
  "lib/notifications/history": typeof lib_notifications_history;
  "lib/permissionSnapshot": typeof lib_permissionSnapshot;
  "lib/platform/accountDeletion": typeof lib_platform_accountDeletion;
  "lib/platform/usageTracking": typeof lib_platform_usageTracking;
  "lib/points/notifyPointsBadgeAlert": typeof lib_points_notifyPointsBadgeAlert;
  "lib/points/pointsBadgeAlert": typeof lib_points_pointsBadgeAlert;
  "lib/points/pointsBadgeAlertSchema": typeof lib_points_pointsBadgeAlertSchema;
  "lib/points/pointsBadgeWindow": typeof lib_points_pointsBadgeWindow;
  "lib/points/pointsLedger": typeof lib_points_pointsLedger;
  "lib/points/pointsRoster": typeof lib_points_pointsRoster;
  "lib/pointsBadgeWindow": typeof lib_pointsBadgeWindow;
  "lib/pointsCleanup": typeof lib_pointsCleanup;
  "lib/pointsRoster": typeof lib_pointsRoster;
  "lib/polarEnv": typeof lib_polarEnv;
  "lib/polarErrors": typeof lib_polarErrors;
  "lib/polarSubscription": typeof lib_polarSubscription;
  "lib/presenceEnabled": typeof lib_presenceEnabled;
  "lib/purchaseLimit": typeof lib_purchaseLimit;
  "lib/randomAssignersCleanup": typeof lib_randomAssignersCleanup;
  "lib/rateLimit/rateLimitActions": typeof lib_rateLimit_rateLimitActions;
  "lib/rateLimit/rateLimiter": typeof lib_rateLimit_rateLimiter;
  "lib/rateLimitActions": typeof lib_rateLimitActions;
  "lib/rateLimiter": typeof lib_rateLimiter;
  "lib/raz/razAutoRti": typeof lib_raz_razAutoRti;
  "lib/raz/razLevels": typeof lib_raz_razLevels;
  "lib/razAutoRti": typeof lib_razAutoRti;
  "lib/razLevels": typeof lib_razLevels;
  "lib/release/scheduledRelease": typeof lib_release_scheduledRelease;
  "lib/rewards/purchaseLimit": typeof lib_rewards_purchaseLimit;
  "lib/rewardsCleanup": typeof lib_rewardsCleanup;
  "lib/roster/avatarUrl": typeof lib_roster_avatarUrl;
  "lib/roster/rosterNameFormat": typeof lib_roster_rosterNameFormat;
  "lib/roster/seedTestStudents": typeof lib_roster_seedTestStudents;
  "lib/roster/studentRosters": typeof lib_roster_studentRosters;
  "lib/roster/userImage": typeof lib_roster_userImage;
  "lib/rosterNameFormat": typeof lib_rosterNameFormat;
  "lib/seatChartGeometry": typeof lib_seatChartGeometry;
  "lib/seatChartLogic": typeof lib_seatChartLogic;
  "lib/seatLayoutCopy": typeof lib_seatLayoutCopy;
  "lib/seatLayoutTeamSync": typeof lib_seatLayoutTeamSync;
  "lib/seating/classroomLayouts": typeof lib_seating_classroomLayouts;
  "lib/seating/diagnose": typeof lib_seating_diagnose;
  "lib/seating/failureEvidence": typeof lib_seating_failureEvidence;
  "lib/seating/gender": typeof lib_seating_gender;
  "lib/seating/history": typeof lib_seating_history;
  "lib/seating/historyKeys": typeof lib_seating_historyKeys;
  "lib/seating/layoutRosterMatrix": typeof lib_seating_layoutRosterMatrix;
  "lib/seating/layoutStudentHistory": typeof lib_seating_layoutStudentHistory;
  "lib/seating/mergeAssignments": typeof lib_seating_mergeAssignments;
  "lib/seating/pipeline": typeof lib_seating_pipeline;
  "lib/seating/predicates": typeof lib_seating_predicates;
  "lib/seating/runSeatingAlgorithm": typeof lib_seating_runSeatingAlgorithm;
  "lib/seating/scope": typeof lib_seating_scope;
  "lib/seating/seatChartGeometry": typeof lib_seating_seatChartGeometry;
  "lib/seating/seatChartLogic": typeof lib_seating_seatChartLogic;
  "lib/seating/seatLayoutCopy": typeof lib_seating_seatLayoutCopy;
  "lib/seating/seatLayoutTeamSync": typeof lib_seating_seatLayoutTeamSync;
  "lib/seating/seatingScenarios": typeof lib_seating_seatingScenarios;
  "lib/seating/seatingSeeds": typeof lib_seating_seatingSeeds;
  "lib/seating/seatingTestHelpers": typeof lib_seating_seatingTestHelpers;
  "lib/seating/settings": typeof lib_seating_settings;
  "lib/seating/solve": typeof lib_seating_solve;
  "lib/seating/types": typeof lib_seating_types;
  "lib/seating/validateOutput": typeof lib_seating_validateOutput;
  "lib/seating/validators": typeof lib_seating_validators;
  "lib/seedTestStudents": typeof lib_seedTestStudents;
  "lib/selfHosted": typeof lib_selfHosted;
  "lib/studentRosters": typeof lib_studentRosters;
  "lib/tasks/migrateWorksheetImage": typeof lib_tasks_migrateWorksheetImage;
  "lib/tasks/taskSchema": typeof lib_tasks_taskSchema;
  "lib/tasksCleanup": typeof lib_tasksCleanup;
  "lib/timetable/importFromClass": typeof lib_timetable_importFromClass;
  "lib/timetable/lessonEvents": typeof lib_timetable_lessonEvents;
  "lib/timetable/sectionItems": typeof lib_timetable_sectionItems;
  "lib/timetable/sectionMigration": typeof lib_timetable_sectionMigration;
  "lib/timetable/slotDisableScope": typeof lib_timetable_slotDisableScope;
  "lib/timetable/slotLinks": typeof lib_timetable_slotLinks;
  "lib/timetable/slotTiming": typeof lib_timetable_slotTiming;
  "lib/timetable/timetableFormSchema": typeof lib_timetable_timetableFormSchema;
  "lib/timetable/timetableSchema": typeof lib_timetable_timetableSchema;
  "lib/trial": typeof lib_trial;
  "lib/uploadPresets": typeof lib_uploadPresets;
  "lib/usageTracking": typeof lib_usageTracking;
  "lib/userImage": typeof lib_userImage;
  "lib/zipEntries": typeof lib_zipEntries;
  linkAccessibility: typeof linkAccessibility;
  members: typeof members;
  migrations: typeof migrations;
  notificationHistoryBackfill: typeof notificationHistoryBackfill;
  notificationHooks: typeof notificationHooks;
  notifications: typeof notifications;
  permissions: typeof permissions;
  points: typeof points;
  polar: typeof polar;
  polarReconcile: typeof polarReconcile;
  presence: typeof presence;
  push: typeof push;
  pushActions: typeof pushActions;
  pushInternal: typeof pushInternal;
  randomAssigners: typeof randomAssigners;
  raz: typeof raz;
  rewardFolders: typeof rewardFolders;
  rewards: typeof rewards;
  seatCharts: typeof seatCharts;
  seatChartsRepair: typeof seatChartsRepair;
  seatConstraints: typeof seatConstraints;
  seatLayoutAggregatesBackfill: typeof seatLayoutAggregatesBackfill;
  seatLayoutGenderParityBackfill: typeof seatLayoutGenderParityBackfill;
  seatLayouts: typeof seatLayouts;
  studentRosters: typeof studentRosters;
  tasks: typeof tasks;
  timetable: typeof timetable;
  trial: typeof trial;
  trialBackfill: typeof trialBackfill;
  usage: typeof usage;
  users: typeof users;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;

export declare const components: {
  authz: import("@djpanda/convex-authz/_generated/component.js").ComponentApi<"authz">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  polar: import("@convex-dev/polar/_generated/component.js").ComponentApi<"polar">;
  presence: import("@convex-dev/presence/_generated/component.js").ComponentApi<"presence">;
  notification: import("convex-notification/_generated/component.js").ComponentApi<"notification">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  usageByKind: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usageByKind">;
  usageByDownloadOs: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usageByDownloadOs">;
  githubClones: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"githubClones">;
};
