import { DAY, HOUR, MINUTE, RateLimiter, WEEK } from "@convex-dev/rate-limiter";

import { components } from "../../_generated/api.js";

const rateLimits = {
  classCreate: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  classCreateGlobal: { kind: "token bucket" as const, rate: 60, period: MINUTE, capacity: 20 },
  classUpdate: { kind: "token bucket" as const, rate: 30, period: MINUTE, capacity: 5 },
  classArchive: { kind: "token bucket" as const, rate: 20, period: MINUTE, capacity: 5 },
  classDelete: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 2 },
  classTransferOwnership: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 2 },
  accountDelete: { kind: "token bucket" as const, rate: 5, period: HOUR, capacity: 1 },
  signOutOtherSessions: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  adminResetPassword: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  adminSeedTestStudents: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  joinCodeCreate: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 5 },
  /** One charge per bulk print, not per student — a 40-student class is one call. */
  guardianInviteCreate: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  joinCodeRevoke: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 10 },
  joinCodeRedeemShort: {
    kind: "token bucket" as const,
    rate: 5,
    period: 5 * MINUTE,
    capacity: 5,
  },
  joinCodeRedeemHourly: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 30 },
  /** Shared across all users — bounds distributed join-code guessing. */
  joinCodeRedeemGlobal: { kind: "token bucket" as const, rate: 200, period: MINUTE, capacity: 50 },
  /** Failure-only counter — successful redeems do not consume this bucket. */
  joinCodeRedeemFailure: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 5 },
  memberSuspend: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 10 },
  memberRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 10 },
  memberSetRole: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 10 },
  memberSetPermission: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 30 },
  memberSetGuardianLinks: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 10 },
  rosterEnsure: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  rosterUpdateFields: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  rosterReorder: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  classUserSettingsUpsert: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  groupCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  groupUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  groupRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  teamCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  teamUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  teamRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  groupAssignStudent: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  groupAssignStudents: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 15 },
  groupClearStudents: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 15 },
  fileUploadUrl: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  fileUploadUrlGlobal: { kind: "token bucket" as const, rate: 120, period: MINUTE, capacity: 40 },
  fileWatchPending: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  fileFinalize: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  fileFinalizeGlobal: { kind: "token bucket" as const, rate: 120, period: MINUTE, capacity: 40 },
  /** Per-user bound for hard reloads; client caches blobs forever under fileId. */
  fileGetBytes: { kind: "token bucket" as const, rate: 200, period: HOUR, capacity: 60 },
  fileGetBytesGlobal: { kind: "token bucket" as const, rate: 600, period: MINUTE, capacity: 120 },
  fileDelete: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  fileRename: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  ensureTrialGrant: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  updateLanguage: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  updateDisplayName: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  updateAvatar: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  clearAvatar: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  billingCheckout: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  billingCheckoutGlobal: { kind: "token bucket" as const, rate: 60, period: MINUTE, capacity: 20 },
  billingPortal: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  billingPortalGlobal: { kind: "token bucket" as const, rate: 60, period: MINUTE, capacity: 20 },
  billingChange: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  billingChangeGlobal: { kind: "token bucket" as const, rate: 60, period: MINUTE, capacity: 20 },
  billingCancel: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 3 },
  billingCancelGlobal: { kind: "token bucket" as const, rate: 60, period: MINUTE, capacity: 20 },
  billingOrders: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  billingOrdersGlobal: { kind: "token bucket" as const, rate: 120, period: MINUTE, capacity: 40 },
  /** Anonymous Free-card download click tracking (prod only). */
  usageTrackDownload: { kind: "token bucket" as const, rate: 10, period: HOUR, capacity: 5 },
  usageTrackDownloadGlobal: {
    kind: "token bucket" as const,
    rate: 120,
    period: MINUTE,
    capacity: 40,
  },
  usageTrackSelfHost: { kind: "token bucket" as const, rate: 5, period: HOUR, capacity: 3 },
  usageTrackSelfHostGlobal: {
    kind: "token bucket" as const,
    rate: 60,
    period: MINUTE,
    capacity: 20,
  },
  /** Cloud feedback form — per signed-in user. */
  feedbackSubmitDaily: { kind: "token bucket" as const, rate: 10, period: DAY, capacity: 10 },
  feedbackSubmitWeekly: { kind: "token bucket" as const, rate: 20, period: WEEK, capacity: 20 },
  /** Intentional education-record access logging from the client. */
  activityLogAccess: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  announcementCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  announcementUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  announcementRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  announcementSetPublic: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  attendanceSave: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  attendanceMarkAbsent: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  calendarEventCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  calendarEventUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  calendarEventRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  pushSubscribe: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  pushUnsubscribe: { kind: "token bucket" as const, rate: 30, period: HOUR, capacity: 10 },
  taskCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  taskUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  taskSetArchived: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  taskRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  taskSetCompletion: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  assignmentCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  assignmentUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  assignmentRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  assignmentLinkAdd: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  assignmentLinkUpdate: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  assignmentLinkRemove: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  assignmentLinkSetHandedIn: {
    kind: "token bucket" as const,
    rate: 240,
    period: HOUR,
    capacity: 60,
  },
  assignmentScoreUpsert: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 80 },
  assignmentScoreClear: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  assignmentScoresSetReleased: {
    kind: "token bucket" as const,
    rate: 60,
    period: HOUR,
    capacity: 30,
  },
  /** Outbound Google/Canva public-share probes before students add links. */
  assignmentLinkAccessCheck: {
    kind: "token bucket" as const,
    rate: 60,
    period: HOUR,
    capacity: 20,
  },
  assignmentLinkAccessCheckGlobal: {
    kind: "token bucket" as const,
    rate: 120,
    period: MINUTE,
    capacity: 40,
  },
  expectationCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  expectationUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  expectationRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  expectationUpsertValue: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  expectationUpsertStudentValues: {
    kind: "token bucket" as const,
    rate: 120,
    period: HOUR,
    capacity: 40,
  },
  expectationBulkApply: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  behaviorFolderCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  behaviorFolderUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  behaviorFolderRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  behaviorCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  behaviorUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  behaviorRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  behaviorImport: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  rewardFolderCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  rewardFolderUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  rewardFolderRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  rewardCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  rewardUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  rewardRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  rewardImport: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  timetableImport: { kind: "token bucket" as const, rate: 20, period: HOUR, capacity: 5 },
  pointsApplyBehaviors: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsRedeemRewards: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsUndoLastAction: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsDeleteLedgerEntry: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsGiveWarning: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsUndoWarning: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 60 },
  pointsClearWarnings: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  attendanceMarkPresent: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  razSetInitialLevel: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  razRecordAssessment: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  razSetManualStatus: { kind: "token bucket" as const, rate: 120, period: HOUR, capacity: 40 },
  seatLayoutCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatLayoutRename: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  seatLayoutRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatLayoutUpdateSettings: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  /** Debounced canvas saves — higher capacity for drag/resize. */
  seatLayoutSaveItems: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 80 },
  seatConstraintCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatConstraintUpdate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  seatConstraintRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatChartCreate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatChartRename: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  seatChartRemove: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 20 },
  seatChartSaveDraft: { kind: "token bucket" as const, rate: 240, period: HOUR, capacity: 80 },
  seatChartRecord: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
  seatChartGenerate: { kind: "token bucket" as const, rate: 60, period: HOUR, capacity: 30 },
};

export const rateLimiter = new RateLimiter(components.rateLimiter, rateLimits);

export type RateLimitName = keyof typeof rateLimits;
