export {
  appendTimerToSession,
  advanceSegment,
  buildCustomTimerSession,
  buildQuickPresetSession,
  buildRotationSession,
  formatCountdown,
  formatEndTimestamp,
  formatPushOverrideRemaining,
  formatPushOverrideRemainingSeconds,
  formatWallTime,
  getCurrentBgColor,
  getCurrentSegment,
  getRotationEndTimes,
  hasUpcomingSegments,
  isLastSegment,
  isPushOverrideActive,
  isRotationSession,
  parseSessionJson,
  remainingFromDisplaySession,
  resolveSegmentDuration,
  truncateUpcomingSegments,
  type ActiveSession,
  type RotationDoc,
  type RotationEndTime,
  type Segment,
  type TimerDoc,
  type TimerEndBehavior,
} from "../../../convex/lib/classroomScreen/activeSession";
